# Generated by Django 5.0 on 2025-02-03 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'venue',
                'unique_together': {('name', 'location')},
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('capacity', models.IntegerField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tracks', to='track.venue')),
            ],
            options={
                'db_table': 'track',
                'unique_together': {('venue', 'name')},
            },
        ),
    ]
