# Generated by Django 5.0 on 2025-02-03 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='roles',
            new_name='role',
        ),
    ]
