# Generated by Django 5.0 on 2025-02-03 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('session_management', '0006_speaker_alter_event_speakers'),
        ('users', '0002_rename_roles_speaker_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Speaker',
        ),
    ]
