# Generated by Django 5.0 on 2025-02-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session_management', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='speaker',
            field=models.ManyToManyField(related_name='speaker_session', to='users.speaker'),
        ),
    ]
