# Generated by Django 5.0 on 2025-02-03 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session_management', '0001_initial'),
        ('track', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_attendee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='track_events', to='track.track'),
        ),
        migrations.AddField(
            model_name='session',
            name='events',
            field=models.ManyToManyField(related_name='sessions', to='session_management.event'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendees', to='session_management.session'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='speaker_profile', to='users.profile'),
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(related_name='speaker_events', to='session_management.speaker'),
        ),
    ]
