# Generated by Django 5.0 on 2025-02-03 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session_management', '0003_attendee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='event',
            new_name='events',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='speaker',
            new_name='speakers',
        ),
    ]
