# Generated by Django 5.0 on 2025-02-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_management', '0004_rename_event_session_events_and_more'),
        ('users', '0002_rename_roles_speaker_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='speakers',
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(related_name='speaker_session', to='users.speaker'),
        ),
    ]
