# Generated by Django 5.0 on 2025-02-03 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_management', '0005_remove_session_speakers_event_speakers'),
        ('users', '0002_rename_roles_speaker_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('host', 'Host'), ('participant', 'Prefer Not to Say')], default='host', max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='speaker_profile', to='users.profile')),
            ],
            options={
                'db_table': 'speaker',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(related_name='speaker_events', to='session_management.speaker'),
        ),
    ]
