# Generated by Django 5.0 on 2025-01-31 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session_management', '0001_initial'),
        ('track', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='speaker',
            field=models.ManyToManyField(related_name='speaker_session', to='users.speaker'),
        ),
        migrations.AddField(
            model_name='session',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='track_sessions', to='track.track'),
        ),
    ]
