name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  #build:
    #needs: test
   # runs-on: ubuntu-latest
    #if: ${{ success() }}
   # steps:
   # - uses: actions/checkout@v4
    #- name: Build the Docker image
   #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: pytest
      continue-on-error: ${{ always() }} # Continue running even if tests fail

    - name: Build Docker image
      if: ${{ success() }} # Execute if previous step (unit test) is successful
      run: |
        # Add your Docker build commands here
        # For example, build a Docker image
        # docker build -t my-image .
        #echo "Docker image built successfully"
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
     # continue-on-error: ${{ always() }} # Continue even if image build fails
        
  

  
