name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  #build:
    #needs: test
   # runs-on: ubuntu-latest
    #if: ${{ success() }}
   # steps:
   # - uses: actions/checkout@v4
    #- name: Build the Docker image
   #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
  test-and-build:
    env: 
      IMAGE_NAME: evms
      PROJECT_ID: valiant-ocean-450906-j4
      
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env: 
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5433:5433
        options: >-
          --health-cmd "pg_isready -U testuser -d testdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@main 
      with: 
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: True

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with coverage
      env: 
        DATABASE_URL: postgres://testuser:testpassword@localhost/testdb
      run: | 
        coverage-3.10 run --source='.' manage.py test api
        coverage report -m
        coverage xml
    - name: Check test coverage meets threshold
      id: coverage
      run: |
        COVERAGE=$(coverage xml -o - | xmllint --xpath "string(//coverage/@line-rate)" -)
        THRESHOLD=0.80
        if (( $(echo "$COVERAGE < $THRESHOLD" | bc -l) )); then
          echo "Test coverage ($COVERAGE) is below the threshold ($THRESHOLD)."
          exit 1
        fi
    #- name: Run unit tests
      #run: python manage.py test
      #continue-on-error: ${{ always() }} # Continue running even if tests fail

    - name: Build Docker image
      if: success()
      #if: ${{ success() }} # Execute if previous step (unit test) is successful
      run: |
        # Add your Docker build commands here
        # For example, build a Docker image
        # docker build -t my-image .
        #echo "Docker image built successfully"
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
     # continue-on-error: ${{ always() }} # Continue even if image build fails

    - name: Configure Docker Client
      if: success()
      run: |-
        gcloud auth configure-docker --quiet

    #- name: Push Docker Image to GCR (Container Registry)
    #  env: 
    #    GIT_TAG: v0.1.0
    #  run: |-
    #    docker tag $IMAGE_NAME:latest.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
    #    docker tag $IMAGE_NAME:latest.gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
    #    docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
    #    docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
  

  
