name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Run python test 
    runs-on: ubuntu-latest
    steps:
    - name: install, and test
      run: |
        pip install -r ../requirements.txt
        python ../manage.py run test
        
  build:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  
