name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  #build:
    #needs: test
   # runs-on: ubuntu-latest
    #if: ${{ success() }}
   # steps:
   # - uses: actions/checkout@v4
    #- name: Build the Docker image
   #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
  test-and-build:
    env: 
      IMAGE_NAME: evms
      PROJECT_ID: valiant-ocean-450906-j4
      
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@main 
      with: 
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: True

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run tests with coverage
      run: | 
        pytest --cov=./ --cov-report=xml
    - name: Check test coverage meets threshold
      id: coverage
      run: |
        COVERAGE=$(xmllint --xpath "string(//coverage/@line-rate)" coverage.xml)
        THRESHOLD=0.80
        if (( $(echo "$COVERAGE < $THRESHOLD" | bc -l) )); then
          echo "Test coverage ($COVERAGE) is below the threshold ($THRESHOLD)."
          exit 1
        fi
      continue-on-error: false
    #- name: Run unit tests
      #run: python manage.py test
      #continue-on-error: ${{ always() }} # Continue running even if tests fail

    - name: Build Docker image
      if: success()
      #if: ${{ success() }} # Execute if previous step (unit test) is successful
      run: |
        # Add your Docker build commands here
        # For example, build a Docker image
        # docker build -t my-image .
        #echo "Docker image built successfully"
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
     # continue-on-error: ${{ always() }} # Continue even if image build fails

    - name: Configure Docker Client
      if: success()
      run: |-
        gcloud auth configure-docker --quiet

    #- name: Push Docker Image to GCR (Container Registry)
    #  env: 
    #    GIT_TAG: v0.1.0
    #  run: |-
    #    docker tag $IMAGE_NAME:latest.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
    #    docker tag $IMAGE_NAME:latest.gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
    #    docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
    #    docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
  

  
